### ISSUE TITLE
Verified checksums and signature

### ISSUE THREAD

**Issue by federicociro** [BcnBitcoinOnly/ordisrespector-binaries#3]
Hi @1ma, 
I compiled and verified the same SHA256sum for the x86_64-linux-gnu architecture binaries. 

You can query my GPG key from [here](https://keys.openpgp.org/vks/v1/by-fingerprint/423A87EDA398FD30E6614FF1B4B16B2D677120AF)

Kind regards,
Federico.

**Comment by 1ma** [comment]
W00t! Thanks, Fede! https://github.com/BcnBitcoinOnly/ordisrespector-binaries/commit/c40b85c4363d4d8c369f92cfc529756d8e9870c3
